[package]
authors = ["Rafael Varago <varago.rafael@gmail.com>"]
edition = "2018"
name = "tokio-codec-experiment"
version = "0.1.0"

[dependencies]
anyhow = "1.0.34"
bytes = "0.6.0"
env_logger = "0.8.2"
futures = "0.3.8"
log = "0.4.11"
structopt = "0.3.20"
tokio = {version = "0.3.4", features = ["full"]}
tokio-util = {version = "0.5.0", features = ["codec"]}
